### ISSUE TITLE
STABLE-SORT fails on empty vectors (1.7.0)

### ISSUE THREAD

**Issue by pfdietz** [armedbear/abcl#230] opened 2020-06-04 14:48 UTC
(stable-sort (make-array '(0)) '<)

==>

Invalid array index 0 for #()
   [Condition of type TYPE-ERROR]

**Comment by easye** [comment] 2020-06-04 15:03
Thanks for the test.  The implementation code for the empty vector/array abstraction could use some love: I bet that's where the problem is.

**Comment by easye** [comment] 2020-06-11 12:33
Fixed with <https://github.com/armedbear/abcl/pull/235>

**Closed by easye** 2020-06-11 12:33 UTC
